spring:
  # konfigurasi untuk koneksi db
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

    # sesuaikan nama database anda dengan di bawah ini
    url: jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQLDATABASE}

    # sesuaikan dengan NAMA dan PASSWORD anda dengan username password di bawah ini
    username: ${MYSQLUSER}
    password: ${MYSQLPASSWORD}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

    # pembuatan database (create || create-drop || validate || update)
    hibernate.ddl-auto: update

    show-sql: true

  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true
cloudinary:
  api_key: ${CLOUDINARY_API_KEY}
  secret_key: ${CLOUDINARY_SECRET_KEY}
  cloud_name: ${CLOUDINARY_CLOUD_NAME}